version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo building the Counties Power User Registration API
      - mvn install
artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'