version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo building the Counties Power User Registration API
      - mvn package
artifacts:
  files:
    - target/register-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'